config/routes.rb
RedmineApp::Application.routes.draw do
  resources :digest_rules, only: [:new, :create, :edit, :update, :destroy, :show]
end

app/models/digest_rule.rb
class DigestRule < ActiveRecord::Base
  ALL                     = 'all'
  SELECTED                = 'selected'
  NOT_SELECTED            = 'not_selected'
  MEMBER                  = 'member'
  MEMBER_NOT_SELECTED     = 'member_not_selected'
  ALL_INVOLVED            = 'all_involved'
  PROJECT_SELECTOR_VALUES = [ALL, SELECTED, NOT_SELECTED, MEMBER, MEMBER_NOT_SELECTED, ALL_INVOLVED]

  NOTIFY_AND_DIGEST = 'all'
  NOTIFY_ONLY       = 'notify'
  DIGEST_ONLY       = 'digest'
  NOTIFY_OPTIONS    = [NOTIFY_AND_DIGEST, NOTIFY_ONLY, DIGEST_ONLY]

  DAILY           = 'daily'
  WEEKLY          = 'weekly'
  MONTHLY         = 'monthly'
  RECURRENT_TYPES = [DAILY, WEEKLY, MONTHLY]

  TEMPLATE_SHORT    = 'short'
  TEMPLATE_DETAIL   = 'detail'
  TEMPLATE_TIMELINE = 'timeline'
  TEMPLATES         = [TEMPLATE_SHORT, TEMPLATE_DETAIL, TEMPLATE_TIMELINE]

  belongs_to :user

  serialize :project_ids, Array
  serialize :event_ids

  attr_accessible :active, :name, :raw_project_ids, :project_selector,
                  :notify, :recurrent, :event_ids, :move_to, :template

  validates :name, presence: true
  validates :project_selector, inclusion: { in: PROJECT_SELECTOR_VALUES }
  validates :notify, inclusion: { in: NOTIFY_OPTIONS }
  validates :recurrent, inclusion: { in: RECURRENT_TYPES }
  validates :template, inclusion: { in: TEMPLATES }

  scope :active, -> { joins(:user).where("active = ? AND #{ User.table_name }.status = ?", true, User::STATUS_ACTIVE) }

  scope :digest_only, -> { where('notify = ?', DIGEST_ONLY) }

  scope :daily, -> { where(recurrent: DAILY) }
  scope :weekly, -> { where(recurrent: WEEKLY) }
  scope :monthly, -> { where(recurrent: MONTHLY) }

  after_initialize :set_default_values

  def raw_project_ids=(comma_seperated_ids)
    self.project_ids = comma_seperated_ids.to_s.split ','
  end

  def raw_project_ids
    project_ids.join ','
  end

  def event_type_enabled?(event_type)
    event_types.include? event_type.to_sym
  end

  def event_types
    event_ids ? event_ids.map(&:to_sym) : []
  end

  def add_event_type(event_type)
    event_ids << event_type.to_s
  end

  def affected_project_ids
    Project.
      joins(:memberships).
      where(get_projects_scope).
      uniq.pluck('projects.id')
  end

  def calculate_time_from(time_to)
    case recurrent
      when DAILY
        time_to - 1.day
      when WEEKLY
        time_to - 1.week
      when MONTHLY
        time_to - 1.month
      else
        raise DigestError.new "Unknown recurrent type (#{recurrent})"
    end
  end

  def find_events_by_journal(journal)
    return [] unless affected_project_ids.include?(journal.issue.project_id)

    events = []

    issue_id   = journal.issue.id
    created_on = journal.created_on
    user       = journal.user

    if journal.notes.present? && event_type_enabled?(DigestEvent::COMMENT_ADDED)
      events << DigestEventFactory.new_event(
        DigestEvent::COMMENT_ADDED, issue_id, created_on, user, journal)
    end

    journal.details.each do |jdetail|
      event = event_for_journal_detail(journal, jdetail)
      events << event if event && event_type_enabled?(event.event_type)
    end

    events
  end

  def apply_for_created_issue?(issue)
    event_type_enabled?(DigestEvent::ISSUE_CREATED) &&
      affected_project_ids.include?(issue.project_id)
  end

  def apply_for_updated_issue?(journal)
    find_events_by_journal(journal).any?
  end

  def notify_and_digest?
    notify == NOTIFY_AND_DIGEST
  end

  def notify_only?
    notify == NOTIFY_ONLY
  end

  def digest_only?
    notify == DIGEST_ONLY
  end

  def all_involved_only?
    project_selector == ALL_INVOLVED
  end

  private

  def event_for_journal_detail(journal, jdetail)
    issue_id   = journal.journalized_id
    created_on = journal.created_on
    user       = journal.user

    if jdetail.property == 'attr' && DigestEvent::PROP_KEYS.has_key?(jdetail.prop_key)
      event_type = DigestEvent::PROP_KEYS[jdetail.prop_key]
      return DigestEventFactory.new_event(event_type, issue_id, created_on, user, journal, jdetail)
    end

    if jdetail.property == 'attachment'
      return DigestEventFactory.new_event(
        DigestEvent::ATTACHMENT_ADDED, issue_id, created_on, user, journal, jdetail)
    end

    DigestEventFactory.new_event(
      DigestEvent::OTHER_ATTR_CHANGED, issue_id, created_on, user, journal, jdetail)
  end

  def get_projects_scope
    case project_selector
      when ALL, ALL_INVOLVED
        nil
      when SELECTED
        ['projects.id in (?)', project_ids]
      when NOT_SELECTED
        ['projects.id not in (?)', project_ids]
      when MEMBER
        ['members.user_id = ?', user.id]
      when MEMBER_NOT_SELECTED
        ['members.user_id = ? and projects.id not in (?)', user.id, project_ids]
      else
        raise RedmineDigest::Error.new "Unknown project selector (#{project_selector})"
    end
  end

  def set_default_values
    self.active           = true if active.nil?
    self.project_selector ||= MEMBER
    self.notify           ||= NOTIFY_AND_DIGEST
    self.recurrent        ||= WEEKLY
    self.event_ids        ||= DigestEvent::TYPES.dup
    self.template         ||= TEMPLATE_SHORT
  end
end

app/controllers/digest_rules_controller.rb
class DigestRulesController < ApplicationController

  PREVIEW_ISSUE_LIMIT = 20

  before_filter :set_user

  def new
    @digest_rule = @user.digest_rules.build
  end

  def create
    @digest_rule = @user.digest_rules.build(params[:digest_rule])
    if @digest_rule.save
      redirect_to controller: 'my', action: 'account'
    else
      render action: 'new'
    end
  end

  def edit
    @digest_rule = DigestRule.find(params[:id])
  end

  def update
    @digest_rule = DigestRule.find(params[:id])
    if @digest_rule.update_attributes(params[:digest_rule])
      redirect_to controller: 'my', action: 'account'
    else
      render action: 'edit'
    end
  end

  def destroy
    digest_rule = DigestRule.find(params[:id])
    digest_rule.destroy
    redirect_to controller: 'my', action: 'account'
  end

  def show
    #digest_rule = @user.digest_rules.find(params[:id])
    digest_rule = DigestRule.find(params[:id])
    @digest     = RedmineDigest::Digest.new(digest_rule, Time.now, PREVIEW_ISSUE_LIMIT)
    render layout: 'digest'
  end

  private

  def set_user
    @user = User.current
  end
end

app/helpers/digest_rules_helper.rb
module DigestRulesHelper
  def project_selector_options_for_select
    DigestRule::PROJECT_SELECTOR_VALUES.map do |v|
      [l(v, scope: 'project_selector'), v]
    end
  end

  def project_ids_options_for_select
    user_projects    = User.current.memberships.collect(&:project).compact.select(&:active?).uniq
    visible_projects = Project.active.visible
    active_projects  = Project.active
    root_projects    = Project.cache_children(active_projects).sort
    result           = []
    result << {
      text:     l(:label_my_projects),
      children: projects_tree_for_selector(root_projects,
                                           only:    user_projects,
                                           allowed: visible_projects)
    }
    result << {
      text:     l(:description_choose_project),
      children: projects_tree_for_selector(root_projects,
                                           only:    visible_projects,
                                           allowed: visible_projects)
    }
    result
  end

  # expected option keys are:
  #  only: []    - array of projects that will be included in tree
  #  except: []  - array of projects that will be excluded from tree
  def projects_tree_for_selector(projects, options = {})
    result = []
    projects.each do |project|

      children      = project.cached_children.sort
      children_tree = projects_tree_for_selector(children, options)

      node = {}

      node.merge!(
        text: project.name
      ) if show_project_as_leaf?(project, options)

      node.merge!(
        text:     project.name,
        children: children_tree
      ) if children_tree.any?

      node.merge!(
        id: project.id
      ) if !node.empty? && allowed_to_select?(project, options)

      result << node unless node.empty?
    end
    result
  end

  def notify_options_for_select
    DigestRule::NOTIFY_OPTIONS.map do |v|
      [l(v, scope: 'notify_options'), v]
    end
  end

  def recurrent_options_for_select
    DigestRule::RECURRENT_TYPES.map do |v|
      [l(v, scope: 'recurrent_types'), v]
    end
  end

  def templates_for_select
    DigestRule::TEMPLATES.map do |v|
      [l(v, scope: 'digest_template'), v]
    end
  end

  def event_type_id(event_type)
    "digest_rule_event_type_#{event_type}"
  end

  def digest_issue_url(di)
    {
      host:       Setting.host_name,
      protocol:   Setting.protocol,
      controller: 'issues',
      action:     'show',
      id:         di.id
    }
  end

  def digest_issue_text(di, show_project_name = true)
    if show_project_name
      "##{di.id} [#{di.project_name}] #{di.subject}"
    else
      "##{di.id} #{di.subject}"
    end
  end

  def digest_issue_title(di)
    [
      di.new_issue? ?
        "#{l(:label_issue_added)} #{format_time(di.created_on)}" : nil,
      di.changes_event_types.any? ?
        "#{l(:label_issue_updated)} #{format_time(di.last_updated_on)}" : nil
    ].compact.join(', ')
  end

  def event_type_color(event_type)
    case event_type
      when DigestEvent::STATUS_CHANGED then
        '#defff1'
      when DigestEvent::PERCENT_CHANGED then
        '#d8d8ff'
      when DigestEvent::ASSIGNEE_CHANGED then
        '#fbe3ff'
      when DigestEvent::VERSION_CHANGED then
        '#ffe1e3'
      when DigestEvent::PROJECT_CHANGED then
        '#fffcde'
      when DigestEvent::SUBJECT_CHANGED then
        '#FF8E8E'
      when DigestEvent::OTHER_ATTR_CHANGED then
        '#E7E9E6'
      when DigestEvent::COMMENT_ADDED then
        '#e0ffe1'
      when DigestEvent::ATTACHMENT_ADDED then
        '#DFF3FF'
      when DigestEvent::ISSUE_CREATED then
        '#e1ffe3'
      else
        'gray'
    end
  end

  def digest_issue_changes_timeline(digest_issue)
    all_changes = digest_issue.changes.sort { |a, b| a.created_on <=> b.created_on }
    all_changes.group_by(&:created_on)
  end

  def digest_event_diff(event)
    diff_with_classes = Redmine::Helpers::Diff.new(event.value, event.old_value).to_html
    diff_with_classes.
      gsub(/class="diff_in"/, 'style="background: #afa;"').
      gsub(/class="diff_out"/, 'style="background: #faa;"').html_safe
  end

  def format_event_text(event)
    case event.event_type
      when DigestEvent::DESCRIPTION_CHANGED
        simple_format_without_paragraph digest_event_diff(event)
      when DigestEvent::COMMENT_ADDED
        simple_format_without_paragraph event.formatted_value
      else
        event.formatted_value
    end
  end

  private

  def show_project_as_leaf?(project, options = {})
    return false if options[:except] && options[:except].include?(project)
    return options[:only].include?(project) if options[:only]
    true
  end

  def allowed_to_select?(project, options = {})
    options[:allowed] ? options[:allowed].include?(project) : false
  end
end

app/views/digest_rules/_digest.html.erb
<h1 style="color: #555; font-family: 'Trebuchet MS', Verdana, sans-serif; padding: 2px 10px 1px 0; margin: 0 0 10px 0; font-size: 2em;">
  <%= digest.name %>
</h1>

<h2 style="color: #555; font-family: 'Trebuchet MS', Verdana, sans-serif; padding: 2px 10px 1px 0; margin: 0 0 10px 0; font-size: 1.4em;">
  <%= t :text_digest,
          :recurrent => t(digest.recurrent, :scope => 'recurrent_types'),
          :time_from => format_date(digest.time_from),
          :time_to => format_date(digest.time_to) %>
</h2>

<% if digest.projects_count == 1 %>
  <h3 style="color: #555; font-family: 'Trebuchet MS', Verdana, sans-serif; padding: 2px 10px 1px 0; margin: 0 0 10px 0; font-size: 1.2em;">
    <%= "#{l(:field_project)}: #{digest.project_names.first}" %>
  </h3>
<% end %>

<div style="font-family: 'Trebuchet MS', Verdana, sans-serif;">
  <%= render 'digest_issues',
             :digest => digest,
             :collection_label => l(:text_new_issues),
             :collection_filter => lambda { |issue| issue.new_issue? } %>

  <%= render 'digest_issues',
             :digest => digest,
             :collection_label => l(:text_changed_issues),
             :collection_filter => lambda { |issue| !issue.new_issue? } %>
</div>

app/views/digest_rules/_digest_issue.html.erb
<tr>
  <td colspan="4" style="padding-top: 10px; font-size: 12pt;">
    <%= link_to digest_issue_url(d_issue),
                :title => digest_issue_title(d_issue),
                :style => 'color: #10152c; text-decoration: none;' do %>
      <%= digest_issue_text(d_issue, digest.many_projects?) %>
    <% end %>
  </td>
</tr>
<% if d_issue.changes_event_types.any? %>
  <%= render 'digest_issue_events', :digest => digest, :d_issue => d_issue %>
<% end %>

app/views/digest_rules/_digest_issue_events.html.erb
<% d_issue.changes_event_types.each do |event_type| %>
  <% last_user_id = nil %>
    <% d_issue.events[event_type].each_with_index do |event, idx| %>
      <tr>
        <% if idx == 0 %>
          <td rowspan="<%= d_issue.events[event_type].length %>" style="width: 10em; text-align: right; border-right: 3px solid #DDDDDD;">
            <%= l(event_type, :scope => 'event_types') %>
          </td>
        <% end %>

        <td style="width: 10em; text-align: center;">
          <% if last_user_id == event.user.id %>
            &nbsp;
          <% else %>
            <%= link_to event.user.name,
                        {
                            :host => Setting.host_name,
                            :protocol => Setting.protocol,
                            :controller => 'users',
                            :action => 'show',
                            :id => event.user.id
                        },
                        :style => 'color: #10152c; text-decoration: none;' %>
          <% end %>
          <% last_user_id = event.user.id %>
        </td>
        <td style="width: 10em;">
          <%= format_time(event.created_on, digest.recurrent != DigestRule::DAILY) %>
        </td>
        <td>
          <% if event_type == DigestEvent::OTHER_ATTR_CHANGED %>
            <%= event.field_label %>:&nbsp;
          <% end %>
          <%= link_to event.formatted_value,
                      {
                          :host => Setting.host_name,
                          :protocol => Setting.protocol,
                          :controller => 'issues',
                          :action => 'show',
                          :id => event.issue_id,
                          :anchor => "note-#{event.indice}"
                      },
                      :title => d_issue.events_summary(event_type),
                      :style => 'color: #10152c; text-decoration: none;' %>
          <% if event.old_value.present? %>
            <span style="color: #9B9B9B; text-decoration: line-through; ">
              <%= event.formatted_old_value %>
            </span>
          <% end %>
        </td>
      </tr>
    <% end %>
<% end %>

app/views/digest_rules/_form.html.erb
<%= error_messages_for 'digest_rule' %>

<div class="box tabular digest-rule">
  <h3><%= l(:label_digest_rule) %></h3>

  <p>
    <%= f.check_box :active %>
  </p>

  <p>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.select :notify, notify_options_for_select %>
  </p>
  <p>
    <%= l(:text_notify) %>
  </p>

  <p class="select2-field">
    <%= f.select :recurrent, recurrent_options_for_select %>
  </p>

  <p class="select2-field">
    <%= f.select :project_selector, project_selector_options_for_select %>
  </p>

  <p id="digest-rule-projects" class="select2-field">
    <%= f.hidden_field :raw_project_ids,
                       data: { options: project_ids_options_for_select } %>
  </p>

  <p>
    <%= f.select :template, templates_for_select %>
  </p>

  <fieldset>
    <legend><%= l(:text_event_types) %></legend>
    <%= hidden_field_tag 'event_ids[]', [] %>

    <% DigestEvent::TYPES.each do |event_type| %>
        <p>
          <%= label_tag event_type_id(event_type), l(event_type, scope: 'event_types') %>
          <%= check_box_tag 'digest_rule[event_ids][]',
                            event_type,
                            f.object.event_type_enabled?(event_type),
                            id: event_type_id(event_type) %>
          <br/>
        </p>
    <% end %>
  </fieldset>
</div>

app/views/digest_rules/_includes.html.erb
<%= stylesheet_link_tag 'redmine_digest', plugin: 'redmine_digest' %>
<%= javascript_include_tag 'redmine_digest', plugin: 'redmine_digest' %>

app/views/digest_rules/_index.html.erb
<%= stylesheet_link_tag 'redmine_digest', plugin: 'redmine_digest' %>
<fieldset class="box digest-rules">
  <legend><%= l(:label_digest_rules_plural) %></legend>
  <div class="contextual">
    <%= link_to l(:new_digest_rule), new_digest_rule_path, class: 'icon icon-add' %>
  </div>

  <%= hidden_field_tag 'digest_rules[active_ids][]', [] %>

  <% if @user.digest_rules.any? %>
      <table class="list">
        <thead>
        <tr>
          <th><%= l(:field_active) %></th>
          <th><%= l(:field_recurrent) %></th>
          <th><%= l(:field_name) %></th>
          <th></th>
        </tr>
        </thead>
        <tbody>
        <% @user.digest_rules.each do |digest_rule| %>
            <tr>
              <td align="center">
                <%= check_box_tag 'digest_rules[active_ids][]', digest_rule.id, digest_rule.active %>
              </td>
              <td align="center"><%= l(digest_rule.recurrent, scope: 'recurrent_types') %></td>
              <td align="center"><%= digest_rule.name %></td>
              <td class="buttons">
                <%= link_to '', digest_rule_path(digest_rule),
                            class: 'icon icon-summary',
                            title: l(:title_digest_preview) %>

                <%= link_to '', edit_digest_rule_path(digest_rule),
                            class: 'icon icon-edit',
                            title: l(:button_edit) %>

                <%= link_to '', digest_rule_path(digest_rule),
                            method:  :delete,
                            confirm: l(:text_are_you_sure),
                            class:   'icon icon-del',
                            title:   l(:button_delete) %>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>
  <% else %>
      <p class="nodata"><%= l(:label_no_data) %></p>
  <% end %>
</fieldset>

<%= javascript_include_tag 'redmine_digest_unsaved', plugin: 'redmine_digest' %>

<%= javascript_tag do %>
  $(window).load(function(){
    warnMyAccountLeavingUnsaved('<%= escape_javascript l(:text_warn_on_leaving_unsaved) %>');
  });
<% end %>

app/views/digest_rules/edit.html.erb
<%= render 'includes' %>

<h2><%= l(:label_digest_rule_edit) %></h2>
<%= labelled_form_for(@digest_rule, url: digest_rule_path(@digest_rule)) do |f| %>
    <%= render partial: 'form', locals: { f: f } %>
    <%= submit_tag l(:button_save) %>
    <%= link_to l(:button_cancel), controller: 'my', action: 'account' %>
<% end %>

app/views/digest_rules/new.html.erb
<%= render 'includes' %>

<h2><%= l(:label_digest_rule_new) %></h2>
<%= labelled_form_for(@digest_rule, url: digest_rules_path) do |f| %>
    <%= render partial: 'form', locals: { f: f } %>
    <%= submit_tag l(:button_save) %>
    <%= link_to l(:button_cancel), controller: 'my', action: 'account' %>
<% end %>

app/views/digest_rules/show.html.erb
<%= render 'digests/digest', digest: @digest %>